# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 21:18
from __future__ import unicode_literals

from django.db import migrations
import django_prices.models
import saleor.product.models.fields
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_stock_quantity_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='attributes', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=django_prices.models.PriceField(currency='INR', decimal_places=2, max_digits=12, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=saleor.product.models.fields.WeightField(decimal_places=2, max_digits=6, unit='gm', verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_override',
            field=django_prices.models.PriceField(blank=True, currency='INR', decimal_places=2, max_digits=12, null=True, verbose_name='price override'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='weight_override',
            field=saleor.product.models.fields.WeightField(blank=True, decimal_places=2, max_digits=6, null=True, unit='gm', verbose_name='weight override'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cost_price',
            field=django_prices.models.PriceField(blank=True, currency='INR', decimal_places=2, max_digits=12, null=True, verbose_name='cost price'),
        ),
    ]
