# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 18:44
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity_topspin',
            field=models.IntegerField(default=Decimal('0'), validators=[django.core.validators.MinValueValidator(0)], verbose_name='topspin quantity'),
        ),
    ]
