# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 09:14
from __future__ import unicode_literals

from django.db import migrations
import django_prices.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20170216_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='attributes', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=django_prices.models.PriceField(currency='INR', decimal_places=2, max_digits=12, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_override',
            field=django_prices.models.PriceField(blank=True, currency='INR', decimal_places=2, max_digits=12, null=True, verbose_name='price override'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cost_price',
            field=django_prices.models.PriceField(blank=True, currency='INR', decimal_places=2, max_digits=12, null=True, verbose_name='cost price'),
        ),
    ]
