# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-20 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20160820_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='to_user',
            field=models.CharField(choices=[('Topspin', 'TOPSPIN'), ('Sachin', 'SACHIN'), ('Sarvotham', 'SARVOTHAM'), ('Anup', 'ANUP')], max_length=20),
        ),
    ]
