# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-20 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20160820_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerStanding',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('order.ledger',),
        ),
    ]
