# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-20 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_ledgerstanding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LedgerStanding',
        ),
    ]
