# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(choices=[('Topspin', 'TOPSPIN'), ('Sachin', 'SACHIN'), ('Sarvotham', 'SARVOTHAM'), ('Anup', 'ANUP')], max_length=20)),
                ('to_user', models.CharField(choices=[('Topspin', 'TOPSPIN'), ('Sachin', 'SACHIN'), ('Sarvotham', 'SARVOTHAM'), ('Anup', 'ANUP')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
    ]
